server:
	port: 8080
	spring:
 application:
   name:greeting-service
	 
	config:
		import:
			- optional: configserver: "url"
		cloud: 
			config:
				profile: qa
management:
  endpoints:
   web:
    exposure:
     include:
      -'*'
greeting-service:
 greeting: "Olá"
   default-value: "Mundo"
