server:
	port: 8888
spring:
	application:
		name: erudio-config-server
		cloud:
			config:
				server:
					git:
						url: "url do git"
						default-label: main
						search-paths:
							- 'greeting-service*'
